# Generated by Django 5.2 on 2025-05-13 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAlojamiento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('camasSimples', models.IntegerField()),
                ('camasDobles', models.IntegerField()),
                ('bañoPrivado', models.BooleanField()),
                ('cocina', models.BooleanField()),
                ('desayuno', models.BooleanField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alojamiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.alojamiento')),
                ('tipoHabitacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tipohabitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantNoches', models.IntegerField()),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField()),
                ('checkIn', models.DateTimeField()),
                ('checkOut', models.DateTimeField()),
                ('nombreHuesped', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField()),
                ('habitacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.habitacion')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodoDePago', models.CharField(max_length=50)),
                ('reserva_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='TipoAlojamiento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tipoalojamiento'),
        ),
    ]
