# Generated by Django 5.2 on 2025-06-20 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alojamiento',
            name='TipoAlojamiento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tipoalojamiento'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='alojamiento_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.alojamiento'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipoHabitacion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tipohabitacion'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='reserva_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='habitacion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.habitacion'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.usuario'),
        ),
    ]
