# Generated by Django 5.2.3 on 2025-07-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_alojamiento_tipoalojamiento_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='usuario_id',
        ),
    ]
