# Generated by Django 5.2.3 on 2025-07-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_reserva_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
