# Generated by Django 5.2.3 on 2025-07-31 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_habitacion_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='habitacion_id',
            new_name='habitacion',
        ),
    ]
