# Generated by Django 5.2.3 on 2025-08-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_habitacion_id_reserva_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='desde',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hasta',
            field=models.DateField(),
        ),
    ]
